unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on
set -s escape-time 0
set -g focus-events on
setw -g xterm-keys on

# Navigasi cepat langsung:
bind -n C-Space select-pane -t :.+
bind -n BTab select-pane -t :.+
bind -n F2 select-pane -t :.+

# Navigasi via Prefix
bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D
bind o select-pane -t :.+

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g status-style bg=black,fg=white
set -g status-left "[#S] "
set -g status-right "%H:%M "
